using System;
using System.Collections.Generic;
using System.Globalization;

namespace DeskMadeline
{
    /// <summary>Supported UI language metadata.</summary>
    internal sealed class LanguageInfo
    {
        public string Code { get; }
        public string NativeName { get; }
        public LanguageInfo(string code, string nativeName)
        {
            Code = code;
            NativeName = nativeName;
        }
    }

    /// <summary>
    /// Key-based UI localization. English is the fallback; other languages are
    /// in-code tables below. To add a language: append a <see cref="LanguageInfo"/>,
    /// add a dictionary entry in <c>translations</c>, and fill every key.
    /// </summary>
    internal static class Loc
    {
        public const string DefaultCode = "en";

        static readonly LanguageInfo[] languages =
        {
            new LanguageInfo("en", "English"),
            new LanguageInfo("zh", "中文"),
        };

        // English fallback table (also the canonical key list).
        static readonly Dictionary<string, string> english = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["App.Name"] = "Madeline",
            ["App.Title"] = "Desk Madeline",
            ["Common.Remove"] = "Remove",
            ["Common.Off"] = "Off",
            ["Common.On"] = "On",
            ["Common.Horizontal"] = "Horizontal",
            ["Common.Vertical"] = "Vertical",
            ["Common.Exit"] = "Exit",
            ["Common.Ok"] = "OK",
            ["Common.Cancel"] = "Cancel",
            ["Common.Close"] = "Close",
            ["Menu.About"] = "About",
            ["Update.Title"] = "Check for Updates",
            ["Update.Checking"] = "Asking GitHub which build is newest...",
            ["Update.Available"] = "There is a newer build.",
            ["Update.Current"] = "This is the newest build.",
            ["Update.Failed"] = "Could not ask GitHub which build is newest.",
            ["Update.NoBuilds"] = "No build has been published yet.",
            ["Update.YoursLabel"] = "This build",
            ["Update.NewestLabel"] = "Newest build",
            ["Update.Unknown"] = "not built from a checkout",
            ["Update.OnThePage"] = "It is on the release page on GitHub.",
            ["Update.Download"] = "Download",
            ["Update.OnGitHub"] = "Download on GitHub",
            ["Update.Install"] = "Update",
            ["Update.Manually"] = "Manually Check on GitHub",
            ["Update.Downloading"] = "Downloading the new build...",
            ["Update.Progress"] = "{0} of {1}  ·  {2}%",
            ["Update.DownloadFailed"] = "The new build could not be downloaded.",
            ["Update.HandoverFailed"] = "The new build was downloaded but could not be put in place.",
            ["Update.NotABuild"] = "What came down does not look like a build of this.",
            ["Update.Later"] = "Later",
            ["About.CreatedBy"] = "Created by",
            ["About.MaintainedBy"] = "Extended and maintained by",
            ["About.FanProject"] = "A fan project, not affiliated with {0} or its developers.",
            ["About.ThirdParty"] = "Her artwork and sounds are read from your own copy of the game. See THIRD_PARTY_NOTICES.md for the mods this borrows from.",
            ["About.Source"] = "GitHub",
            ["Action.Left"] = "Left",
            ["Action.Right"] = "Right",
            ["Action.Up"] = "Up",
            ["Action.Down"] = "Down",
            ["Action.Jump"] = "Jump",
            ["Action.Dash"] = "Dash",
            ["Action.Grab"] = "Grab",
            ["Action.CrouchDash"] = "Crouch Dash",
            ["Action.DeployElytra"] = "Deploy Elytra",
            ["Keys.Unbound"] = "Unbound",
            ["Keys.Clear"] = "Clear slot",
            ["Keys.BindTitle"] = "Bind {0}",
            ["Keys.CaptureHint"] = "Press a key. Backspace/Delete clears this slot; Esc cancels.",
            ["Pad.CaptureHint"] = "Press a controller button. Backspace/Delete clears this slot; Esc cancels.",
            ["Pad.NoController"] = "No controller detected.",
            ["Pad.A"] = "A",
            ["Pad.B"] = "B",
            ["Pad.X"] = "X",
            ["Pad.Y"] = "Y",
            ["Pad.LeftShoulder"] = "LB (left bumper)",
            ["Pad.RightShoulder"] = "RB (right bumper)",
            ["Pad.LeftTrigger"] = "LT (left trigger)",
            ["Pad.RightTrigger"] = "RT (right trigger)",
            ["Pad.LeftStick"] = "Left stick click",
            ["Pad.RightStick"] = "Right stick click",
            ["Pad.Start"] = "Start",
            ["Pad.Back"] = "Back",
            ["Pad.DPadUp"] = "D-Pad up",
            ["Pad.DPadDown"] = "D-Pad down",
            ["Pad.DPadLeft"] = "D-Pad left",
            ["Pad.DPadRight"] = "D-Pad right",
            ["Pad.LeftStickUp"] = "Left stick up",
            ["Pad.LeftStickDown"] = "Left stick down",
            ["Pad.LeftStickLeft"] = "Left stick left",
            ["Pad.LeftStickRight"] = "Left stick right",
            ["Pad.RightStickUp"] = "Right stick up",
            ["Pad.RightStickDown"] = "Right stick down",
            ["Pad.RightStickLeft"] = "Right stick left",
            ["Pad.RightStickRight"] = "Right stick right",
            ["Menu.Language"] = "Language",
            ["Menu.Skin"] = "Skin",
            ["Skin.Default"] = "Default Madeline",
            ["Skin.Refresh"] = "Refresh skins",
            ["Skin.OpenFolder"] = "Open skins folder",
            ["Skin.OpenFolderFailed"] = "Could not open skins folder",
            ["Menu.Cosmetics"] = "Cosmetics",
            ["Cosmetics.CatTail"] = "Cat tail",
            ["Cosmetics.CatBangs"] = "Cat bangs",
            ["Menu.HairColors"] = "Hair colors",
            ["Hair.UseCustom"] = "Use custom colors",
            ["Hair.NoDashes"] = "No dashes",
            ["Hair.OneDash"] = "One dash",
            ["Hair.TwoDashes"] = "Two dashes",
            ["Hair.ResetCeleste"] = "Reset Celeste colors",
            ["Menu.KeyboardControls"] = "Keyboard controls",
            ["Menu.ControllerControls"] = "Controller controls (XInput)",
            ["Menu.RespondUnfocused"] = "Respond while unfocused",
            ["Settings.UnfocusedNote"] = "Madeline reads the keyboard and controller even while another window has focus. That window still gets every key too.",
            ["Settings.GrabHold"] = "Grab while the button is held. Celeste's default.",
            ["Settings.GrabInvert"] = "Grab unless the button is held.",
            ["Settings.GrabToggle"] = "Press once to grab and again to let go. A glove over Madeline shows when grab is on.",
            ["Settings.Bindings"] = "Bindings",
            ["Settings.Keyboard"] = "Keyboard",
            ["Settings.Controller"] = "Controller",
            ["Settings.ResetBindings"] = "Reset All to Defaults",
            ["Settings.BindingsNote"] = "Click a slot, then press the key or button for it. Backspace or Delete clears the slot; Esc leaves it as it was.",
            ["Tab.Madeline"] = "Madeline",
            ["Tab.Environment"] = "Env",
            ["Tab.EnvironmentFull"] = "Environment",
            ["Tab.App"] = "App",
            ["Flyout.Assists"] = "Assists",
            ["Flyout.Variants"] = "Variants",
            ["Tab.Controls"] = "Controls",
            ["Tab.Look"] = "Look",
            ["Tab.Sound"] = "Sound",
            ["Flyout.WakeUp"] = "Wake up",
            ["Flyout.Bindings"] = "Key and button bindings…",
            ["Flyout.Scale"] = "Scale",
            ["Entity.Jellyfish"] = "Jellyfish",
            ["Entity.Seeker"] = "Seeker",
            ["Entity.Theo"] = "Theo crystal",
            ["Entity.Bumper"] = "Bumper",
            ["Entity.Puffer"] = "Pufferfish",
            ["Flyout.RemoveAll"] = "Remove all",
            ["Flyout.Theme"] = "Theme",
            ["Theme.System"] = "System",
            ["Theme.Light"] = "Light",
            ["Theme.Dark"] = "Dark",
            ["Flyout.Updates"] = "Updates",
            ["Flyout.RemoveByType"] = "Remove by type",
            ["Menu.AlwaysOnTop"] = "Always on top",
            ["Menu.LaunchAtSignIn"] = "Launch at sign-in",
            ["Startup.ChangeFailed"] = "Could not change sign-in startup",
            ["Menu.SoundEffects"] = "Sound effects",
            ["Sfx.OnlyWhenFocused"] = "Only when focused",
            ["Sfx.Volume"] = "Volume",
            ["Sfx.SurfaceMaterial"] = "Surface material",
            ["Sfx.WhyNoRuntime"] = "Sound effects unavailable: they are played from a Celeste with Everest installed.",
            ["Sfx.WhyNoBanks"] = "No sound: Celeste's sound banks were not found. Point at the game under Celeste folder.",
            ["Sfx.WhyUnavailable"] = "No sound: FMOD would not start. See pet_debug.log.",
            ["Sfx.Get"] = "Download the sound library…",
            ["Sfx.GetTitle"] = "Sound effects are not available",
            ["Sfx.GetWhy"] = "Desk Madeline plays Celeste's own sound effects. Playing them needs the game's 64-bit FMOD, which comes with a copy of Celeste that has Everest installed, and yours does not have it.\n\nHowever, you can also let Desk Madeline download the library it needs and keep it beside herself; your Celeste folder is not touched.\n\nOr leave her silent: everything else works the same, and this offer stays in the menu, on its Sound tab.",
            ["Sfx.GetFrom"] = "About 1 MB, from Everest's release on GitHub.",
            ["Sfx.Getting"] = "Downloading the sound library…",
            ["Sfx.GetDone"] = "The sound library is in place.",
            ["Sfx.RestartToApply"] = "Restart Desk Madeline now to hear her?",
            ["Sfx.RestartNow"] = "Restart now",
            ["Sfx.GetFailed"] = "The sound library could not be downloaded.",
            ["Sfx.InstallEverest"] = "Install Everest",
            ["Sfx.StaySilent"] = "Stay silent",
            ["Sfx.OnEverest"] = "Everest's page",
            ["Surface.Asphalt"] = "Asphalt",
            ["Surface.Car"] = "Car",
            ["Surface.Dirt"] = "Dirt",
            ["Surface.Snow"] = "Snow",
            ["Surface.Wood"] = "Wood",
            ["Surface.StoneBridge"] = "Stone bridge",
            ["Surface.Girder"] = "Girder",
            ["Surface.BrickDefault"] = "Brick (Default)",
            ["Surface.ZipMover"] = "Zip mover",
            ["Surface.InactiveDreamBlock"] = "Inactive Dream Block",
            ["Surface.ActiveDreamBlock"] = "Active Dream Block",
            ["Surface.ResortWood"] = "Resort wood",
            ["Surface.ResortRoof"] = "Resort roof",
            ["Surface.ResortSinkingPlatform"] = "Resort sinking platform",
            ["Surface.ResortBasementTile"] = "Resort basement tile",
            ["Surface.ResortLinens"] = "Resort linens",
            ["Surface.ResortBoxes"] = "Resort boxes",
            ["Surface.ResortBooks"] = "Resort books",
            ["Surface.ClutterDoor"] = "Clutter door",
            ["Surface.ClutterSwitch"] = "Clutter switch",
            ["Surface.ResortElevator"] = "Resort elevator",
            ["Surface.CliffsideSnow"] = "Cliffside snow",
            ["Surface.CliffsideGrass"] = "Cliffside grass",
            ["Surface.CliffsideWhiteBlock"] = "Cliffside white block",
            ["Surface.Gondola"] = "Gondola",
            ["Surface.AuroraGlass"] = "Aurora glass",
            ["Surface.Grass"] = "Grass",
            ["Surface.CassetteBlock"] = "Cassette block",
            ["Surface.CoreIce"] = "Core ice",
            ["Surface.CoreMoltenRock"] = "Core molten rock",
            ["Surface.Glitch"] = "Glitch",
            ["Surface.MoonCafe"] = "Moon cafe",
            ["Surface.DreamClouds"] = "Dream clouds",
            ["Surface.Moon"] = "Moon",
            ["Menu.ParticleEffects"] = "Particle effects",
            ["Menu.FreezeFrames"] = "Freeze frames",
            ["Menu.RespawnReversal"] = "Respawn reversal animation",
            ["Menu.IgnoreMaximizedWindows"] = "Ignore maximized and fullscreen windows",
            ["Menu.WindowsAre"] = "Windows are",
            ["Windows.Solid"] = "Solid",
            ["Windows.DreamBlocks"] = "Dream Blocks",
            ["Windows.Water"] = "Water",
            ["Windows.MoonBlocks"] = "Moon Blocks",
            ["Windows.KevinBlocks"] = "Kevin Blocks",
            ["Menu.EdgeWrap"] = "Infinite screen edges (Experimental)",
            ["EdgeWrap.Both"] = "Both",
            ["Menu.Elytra"] = "Elytra mode (CommunalHelper)",
            ["Menu.ExtraOverlays"] = "Extra overlays",
            ["Menu.Speedometer"] = "Speedometer",
            ["Speedometer.Both"] = "Both",
            ["Menu.Hitboxes"] = "Hitboxes",
            ["Menu.InfiniteStamina"] = "Infinite stamina",
            ["Menu.Invincible"] = "Invincible",
            ["Menu.SuperDash"] = "Super dashing",
            ["Menu.DashCount"] = "Dash count",
            ["Menu.GrabMode"] = "Grab mode",
            ["GrabMode.Hold"] = "Hold",
            ["GrabMode.Invert"] = "Invert",
            ["GrabMode.Toggle"] = "Toggle",
            ["Menu.ResetPosition"] = "Reset position",
            ["Menu.Autonomy"] = "Wander on her own",
            ["Menu.AutonomyDebug"] = "Autonomy debug",
            ["Menu.Spawn"] = "Spawn",
            ["Celeste.NoneFound"] = "No Celeste installation found",
            ["Celeste.Why"] = "Madeline's sprites and sounds are read from an installed copy of Celeste.",
            ["Celeste.None"] = "none",
            ["Celeste.InUse"] = "In use: {0}",
            ["Celeste.PickFolder"] = "Choose the folder that holds Celeste.exe",
            ["Celeste.NoExeThere"] = "There is no Celeste.exe in that folder.",
            ["Menu.CelesteDetect"] = "Detect Celeste",
            ["Menu.CelesteChoose"] = "Choose folder…",
            ["Celeste.IncompleteTitle"] = "This copy of Celeste is incomplete",
            ["Celeste.UseAnywayButton"] = "Use it anyway",
            ["Celeste.ChooseAgain"] = "Choose again",
            ["Celeste.FoundTitle"] = "Celeste found",
            ["Celeste.Incomplete"] = "The Celeste at {0} is missing files her sprites and sounds are read from:",
            ["Celeste.AndMore"] = "…and {0} more",
            ["Celeste.Without"] = "Running without Celeste's files: Madeline has no sprites and no sounds. Point at the game from the tray icon's menu.",
            ["Celeste.RestartToApply"] = "Restart Desk Madeline now to read her sprites and sounds from the new folder?",
        };

        // Non-English catalogs. Key set should match <see cref="english"/>.
        static readonly Dictionary<string, Dictionary<string, string>> translations =
            new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["zh"] = new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["App.Name"] = "玛德琳",
                ["App.Title"] = "玛德琳桌宠",
                ["Common.Remove"] = "移除",
                ["Common.Off"] = "关闭",
                ["Common.On"] = "开启",
                ["Common.Horizontal"] = "水平",
                ["Common.Vertical"] = "垂直",
                ["Common.Exit"] = "退出",
                ["Common.Ok"] = "确定",
                ["Common.Cancel"] = "取消",
                ["Common.Close"] = "关闭",
                ["Menu.About"] = "关于",
                ["Update.Title"] = "检查更新",
                ["Update.Checking"] = "正在向 GitHub 查询最新构建...",
                ["Update.Available"] = "有更新的构建。",
                ["Update.Current"] = "已是最新构建。",
                ["Update.Failed"] = "无法向 GitHub 查询最新构建。",
                ["Update.NoBuilds"] = "尚未发布任何构建。",
                ["Update.YoursLabel"] = "当前构建",
                ["Update.NewestLabel"] = "最新构建",
                ["Update.Unknown"] = "并非由代码仓库构建",
                ["Update.OnThePage"] = "在 GitHub 的发布页面上。",
                ["Update.Download"] = "下载",
                ["Update.OnGitHub"] = "在 GitHub 下载",
                ["Update.Install"] = "更新",
                ["Update.Manually"] = "在 GitHub 上手动查看",
                ["Update.Downloading"] = "正在下载新构建...",
                ["Update.Progress"] = "{0} / {1}  ·  {2}%",
                ["Update.DownloadFailed"] = "无法下载新构建。",
                ["Update.HandoverFailed"] = "新构建已下载，但无法替换当前版本。",
                ["Update.NotABuild"] = "下载到的内容不像是本项目的构建。",
                ["Update.Later"] = "稍后",
                ["About.CreatedBy"] = "原作者",
                ["About.MaintainedBy"] = "扩展和维护",
                ["About.FanProject"] = "同人项目，与 {0} 及其开发者无关。",
                ["About.ThirdParty"] = "贴图与音效均读取自你自己的游戏副本。本项目借鉴的模组见 THIRD_PARTY_NOTICES.md。",
                ["About.Source"] = "GitHub",
                ["Action.Left"] = "左",
                ["Action.Right"] = "右",
                ["Action.Up"] = "上",
                ["Action.Down"] = "下",
                ["Action.Jump"] = "跳跃",
                ["Action.Dash"] = "冲刺",
                ["Action.Grab"] = "抓取",
                ["Action.CrouchDash"] = "蹲冲",
                ["Action.DeployElytra"] = "展开鞘翅",
                ["Keys.Unbound"] = "未绑定",
                ["Keys.Clear"] = "清除此栏",
                ["Keys.BindTitle"] = "绑定{0}",
                ["Keys.CaptureHint"] = "请按一个键。Backspace/Delete 清除此栏；Esc 取消。",
                ["Pad.CaptureHint"] = "请按一个手柄按键。Backspace/Delete 清除此栏；Esc 取消。",
                ["Pad.NoController"] = "未检测到手柄。",
                ["Pad.A"] = "A",
                ["Pad.B"] = "B",
                ["Pad.X"] = "X",
                ["Pad.Y"] = "Y",
                ["Pad.LeftShoulder"] = "LB（左肩键）",
                ["Pad.RightShoulder"] = "RB（右肩键）",
                ["Pad.LeftTrigger"] = "LT（左扳机）",
                ["Pad.RightTrigger"] = "RT（右扳机）",
                ["Pad.LeftStick"] = "按下左摇杆",
                ["Pad.RightStick"] = "按下右摇杆",
                ["Pad.Start"] = "Start",
                ["Pad.Back"] = "Back",
                ["Pad.DPadUp"] = "十字键上",
                ["Pad.DPadDown"] = "十字键下",
                ["Pad.DPadLeft"] = "十字键左",
                ["Pad.DPadRight"] = "十字键右",
                ["Pad.LeftStickUp"] = "左摇杆上",
                ["Pad.LeftStickDown"] = "左摇杆下",
                ["Pad.LeftStickLeft"] = "左摇杆左",
                ["Pad.LeftStickRight"] = "左摇杆右",
                ["Pad.RightStickUp"] = "右摇杆上",
                ["Pad.RightStickDown"] = "右摇杆下",
                ["Pad.RightStickLeft"] = "右摇杆左",
                ["Pad.RightStickRight"] = "右摇杆右",
                ["Menu.Language"] = "语言",
                ["Menu.Skin"] = "皮肤",
                ["Skin.Default"] = "默认玛德琳",
                ["Skin.Refresh"] = "刷新皮肤",
                ["Skin.OpenFolder"] = "打开皮肤文件夹",
                ["Skin.OpenFolderFailed"] = "无法打开皮肤文件夹",
                ["Menu.Cosmetics"] = "装饰",
                ["Cosmetics.CatTail"] = "猫尾",
                ["Cosmetics.CatBangs"] = "猫耳刘海",
                ["Menu.HairColors"] = "头发颜色",
                ["Hair.UseCustom"] = "使用自定义颜色",
                ["Hair.NoDashes"] = "无冲刺",
                ["Hair.OneDash"] = "一次冲刺",
                ["Hair.TwoDashes"] = "两次冲刺",
                ["Hair.ResetCeleste"] = "恢复原版颜色",
                ["Menu.KeyboardControls"] = "键盘控制",
                ["Menu.ControllerControls"] = "手柄控制（XInput）",
                ["Menu.RespondUnfocused"] = "失焦时也响应输入",
                ["Settings.UnfocusedNote"] = "其他窗口获得焦点时，玛德琳也会读取键盘和手柄。该窗口仍会收到所有按键。",
                ["Settings.GrabHold"] = "按住抓取键时抓取。Celeste 的默认设置。",
                ["Settings.GrabInvert"] = "未按住抓取键时抓取。",
                ["Settings.GrabToggle"] = "按一下开始抓取，再按一下松开。抓取开启时玛德琳头顶会出现手套。",
                ["Settings.Bindings"] = "按键绑定",
                ["Settings.Keyboard"] = "键盘",
                ["Settings.Controller"] = "手柄",
                ["Settings.ResetBindings"] = "重置为默认设置",
                ["Settings.BindingsNote"] = "点击一栏，然后按下要绑定的键或手柄按键。Backspace 或 Delete 清除此栏；Esc 保持不变。",
                ["Tab.Madeline"] = "玛德琳",
                ["Tab.Environment"] = "环境",
                ["Tab.EnvironmentFull"] = "环境",
                ["Tab.App"] = "应用",
                ["Flyout.Assists"] = "协助",
                ["Flyout.Variants"] = "异变",
                ["Tab.Controls"] = "控制",
                ["Tab.Look"] = "外观",
                ["Tab.Sound"] = "声音",
                ["Flyout.WakeUp"] = "唤醒",
                ["Flyout.Bindings"] = "按键与手柄绑定…",
                ["Flyout.Scale"] = "缩放",
                ["Entity.Jellyfish"] = "水母",
                ["Entity.Seeker"] = "Seeker",
                ["Entity.Theo"] = "Theo 水晶",
                ["Entity.Bumper"] = "弹球",
                ["Entity.Puffer"] = "河豚",
                ["Flyout.RemoveAll"] = "全部移除",
                ["Flyout.Theme"] = "主题",
                ["Theme.System"] = "系统",
                ["Theme.Light"] = "浅色",
                ["Theme.Dark"] = "深色",
                ["Flyout.Updates"] = "更新",
                ["Flyout.RemoveByType"] = "按类型移除",
                ["Menu.AlwaysOnTop"] = "总是置顶",
                ["Menu.LaunchAtSignIn"] = "登录时启动",
                ["Startup.ChangeFailed"] = "无法更改登录启动设置",
                ["Menu.SoundEffects"] = "音效",
                ["Sfx.OnlyWhenFocused"] = "仅聚焦时",
                ["Sfx.Volume"] = "音量",
                ["Sfx.SurfaceMaterial"] = "表面材质",
                ["Sfx.WhyNoRuntime"] = "音效不可用：需要安装了 Everest 的 Celeste 副本。",
                ["Sfx.WhyNoBanks"] = "无音效：未找到 Celeste 的音效库。请在“Celeste 文件夹”中指定游戏目录。",
                ["Sfx.WhyUnavailable"] = "无音效：FMOD 未能启动。详见 pet_debug.log。",
                ["Sfx.Get"] = "下载音效库文件…",
                ["Sfx.GetTitle"] = "音效不可用",
                ["Sfx.GetWhy"] = "玛德琳桌宠播放的是 Celeste 原本的音效。播放它们需要游戏的 64 位 FMOD，而只有安装了 Everest 的 Celeste 副本才带有它，你的副本没有。\n\n不过，你也可以让玛德琳桌宠下载所需的库文件，保存在她自己旁边；不会改动你的 Celeste 目录。\n\n也可以让她保持静音：其余一切照常，此提示会保留在菜单的“声音”页中。",
                ["Sfx.GetFrom"] = "约 1 MB，来自 GitHub 上 Everest 的发布。",
                ["Sfx.Getting"] = "正在下载音效库文件…",
                ["Sfx.GetDone"] = "音效库文件已就位。",
                ["Sfx.RestartToApply"] = "现在重启玛德琳桌宠，让她发出声音吗？",
                ["Sfx.RestartNow"] = "立即重启",
                ["Sfx.GetFailed"] = "音效库文件下载失败。",
                ["Sfx.InstallEverest"] = "安装 Everest",
                ["Sfx.StaySilent"] = "保持静音",
                ["Sfx.OnEverest"] = "Everest 页面",
                ["Surface.Asphalt"] = "沥青",
                ["Surface.Car"] = "汽车",
                ["Surface.Dirt"] = "泥土",
                ["Surface.Snow"] = "雪地",
                ["Surface.Wood"] = "木材",
                ["Surface.StoneBridge"] = "石桥",
                ["Surface.Girder"] = "钢梁",
                ["Surface.BrickDefault"] = "砖块（默认）",
                ["Surface.ZipMover"] = "轨道方块",
                ["Surface.InactiveDreamBlock"] = "未激活梦境方块",
                ["Surface.ActiveDreamBlock"] = "激活梦境方块",
                ["Surface.ResortWood"] = "度假村木材",
                ["Surface.ResortRoof"] = "度假村屋顶",
                ["Surface.ResortSinkingPlatform"] = "度假村下沉平台",
                ["Surface.ResortBasementTile"] = "度假村地下室",
                ["Surface.ResortLinens"] = "度假村布料",
                ["Surface.ResortBoxes"] = "度假村纸箱",
                ["Surface.ResortBooks"] = "度假村书本",
                ["Surface.ClutterDoor"] = "杂物门",
                ["Surface.ClutterSwitch"] = "杂物开关",
                ["Surface.ResortElevator"] = "度假村电梯",
                ["Surface.CliffsideSnow"] = "山脊雪地",
                ["Surface.CliffsideGrass"] = "山脊草地",
                ["Surface.CliffsideWhiteBlock"] = "山脊白块",
                ["Surface.Gondola"] = "缆车",
                ["Surface.AuroraGlass"] = "极光玻璃",
                ["Surface.Grass"] = "草地",
                ["Surface.CassetteBlock"] = "磁带方块",
                ["Surface.CoreIce"] = "核心冰面",
                ["Surface.CoreMoltenRock"] = "核心熔岩",
                ["Surface.Glitch"] = "故障方块",
                ["Surface.MoonCafe"] = "月球咖啡馆",
                ["Surface.DreamClouds"] = "梦境云层",
                ["Surface.Moon"] = "月球",
                ["Menu.ParticleEffects"] = "粒子特效",
                ["Menu.FreezeFrames"] = "冻结帧",
                ["Menu.RespawnReversal"] = "重生逆向动画",
                ["Menu.IgnoreMaximizedWindows"] = "忽略最大化和全屏窗口",
                ["Menu.WindowsAre"] = "窗口是",
                ["Windows.Solid"] = "实体平台",
                ["Windows.DreamBlocks"] = "梦境方块",
                ["Windows.Water"] = "水",
                ["Windows.MoonBlocks"] = "月亮块",
                ["Windows.KevinBlocks"] = "凯文方块",
                ["Menu.EdgeWrap"] = "无限屏幕边缘（实验性）",
                ["EdgeWrap.Both"] = "水平和垂直",
                ["Menu.Elytra"] = "鞘翅模式（CommunalHelper）",
                ["Menu.ExtraOverlays"] = "额外叠加层",
                ["Menu.Speedometer"] = "速度计",
                ["Speedometer.Both"] = "合速度",
                ["Menu.Hitboxes"] = "碰撞箱",
                ["Menu.InfiniteStamina"] = "无限体力",
                ["Menu.Invincible"] = "无敌模式",
                ["Menu.SuperDash"] = "超级冲刺",
                ["Menu.DashCount"] = "冲刺次数",
                ["Menu.GrabMode"] = "抓取模式",
                ["GrabMode.Hold"] = "按住",
                ["GrabMode.Invert"] = "反转",
                ["GrabMode.Toggle"] = "切换",
                ["Menu.ResetPosition"] = "重置位置",
                ["Menu.Autonomy"] = "自主活动",
                ["Menu.AutonomyDebug"] = "自主活动调试",
                ["Menu.Spawn"] = "生成",
                ["Celeste.NoneFound"] = "未找到 Celeste 安装目录",
                ["Celeste.Why"] = "玛德琳的贴图与音效读取自已安装的 Celeste。",
                ["Celeste.None"] = "无",
                ["Celeste.InUse"] = "正在使用：{0}",
                ["Celeste.PickFolder"] = "请选择包含 Celeste.exe 的文件夹",
                ["Celeste.NoExeThere"] = "该文件夹中没有 Celeste.exe。",
                ["Menu.CelesteDetect"] = "自动检测 Celeste",
                ["Menu.CelesteChoose"] = "选择文件夹…",
                ["Celeste.IncompleteTitle"] = "这个 Celeste 副本不完整",
                ["Celeste.UseAnywayButton"] = "仍然使用",
                ["Celeste.ChooseAgain"] = "重新选择",
                ["Celeste.FoundTitle"] = "已找到 Celeste",
                ["Celeste.Incomplete"] = "{0} 中的 Celeste 缺少读取贴图与音效所需的文件：",
                ["Celeste.AndMore"] = "……还有 {0} 个",
                ["Celeste.Without"] = "未使用 Celeste 的文件运行：玛德琳没有贴图也没有音效。可稍后在托盘图标的菜单中指定游戏目录。",
                ["Celeste.RestartToApply"] = "现在重启玛德琳桌宠，以从新的文件夹读取贴图与音效吗？",
            },
        };

        static string currentCode = DefaultCode;

        public static string CurrentCode => currentCode;

        public static IReadOnlyList<LanguageInfo> Languages => languages;

        public static bool IsKnown(string code)
        {
            if (string.IsNullOrWhiteSpace(code)) return false;
            foreach (var lang in languages)
                if (lang.Code.Equals(code, StringComparison.OrdinalIgnoreCase)) return true;
            return false;
        }

        /// <summary>Pick initial language from settings or UI culture (zh* → zh, else en).</summary>
        public static string DetectDefault(string settingsCode = null)
        {
            if (IsKnown(settingsCode)) return Normalize(settingsCode);
            string ui = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            if (IsKnown(ui)) return Normalize(ui);
            return DefaultCode;
        }

        public static void SetLanguage(string code)
        {
            currentCode = IsKnown(code) ? Normalize(code) : DefaultCode;
        }

        /// <summary>Translate a catalog key. Missing keys fall back to English, then the key itself.</summary>
        public static string T(string key)
        {
            if (string.IsNullOrEmpty(key)) return key;
            if (TryGet(currentCode, key, out string value)) return value;
            if (english.TryGetValue(key, out value)) return value;
            return key;
        }

        /// <summary>Translate and format with <see cref="string.Format(IFormatProvider, string, object[])"/>.</summary>
        public static string Format(string key, params object[] args)
        {
            string template = T(key);
            if (args == null || args.Length == 0) return template;
            try { return string.Format(CultureInfo.CurrentCulture, template, args); }
            catch (FormatException) { return template; }
        }

        static bool TryGet(string code, string key, out string value)
        {
            value = null;
            if (code.Equals(DefaultCode, StringComparison.OrdinalIgnoreCase))
                return english.TryGetValue(key, out value);
            return translations.TryGetValue(code, out var table) && table.TryGetValue(key, out value);
        }

        static string Normalize(string code)
        {
            foreach (var lang in languages)
                if (lang.Code.Equals(code, StringComparison.OrdinalIgnoreCase)) return lang.Code;
            return code.Trim().ToLowerInvariant();
        }
    }
}
